### ISSUE TITLE
Doesn't respect username/password when set via env

### ISSUE THREAD

**Issue by jasonkarns** [drone-plugins/drone-npm#16]
Npm defines a very explicit hierarchy of ways to build the config that is in effect when npm runs its commands (in reverse priority).

- npm built-in config file (`/path/to/npm/npmrc`)
- global system config file (`$PREFIX/etc/npmrc`)
- user config file (`$NPM_CONFIG_USERCONFIG`, default: `~/.npmrc`)
- per-project config file (/path/to/my/project/.npmrc)
- env vars (`$NPM_CONFIG_*`)
- cli

Obviously the cli doesn't apply when run through drone. However, the env vars *should* be in effect.

However, setting NPM_CONFIG_USERNAME and NPM_CONFIG_PASSWORD environment vars in drone results in an error message:

> Username not provided

I see that this plugin duplicates npm's own env vars (for what reason, I can't imagine):

```
NPM_USERNAME
NPM_PASSWORD
NPM_TOKEN
NPM_EMAIL
NPM_REGISTRY
```

Why are these duplicated when npm already has built-in support for accepting configuration through the environment (and in a general-purpose way, no less)?

The above variables ought to be deprecated in favor of the standard npm vars:

```
NPM_CONFIG_USERNAME
NPM_CONFIG_PASSWORD
NPM_CONFIG_TOKEN
NPM_CONFIG_EMAIL
NPM_CONFIG_REGISTRY
```

**Comment by tboerger** [comment]
We won't change the variable names because that's how we get the secrets from the drone secret store.

**Comment by tboerger** [comment]
If you follow the docs at https://github.com/drone-plugins/drone-npm/blob/master/DOCS.md it's confirmed that it works like expected. Beside that we encourage discussions via gitter about the usage of plugins.

**Comment by bradrydzewski** [comment]
I can't speak to the naming decisions but perhaps @donny-dont can provide further detail. I would advocate using standard environment variables where possible with plugins. I agree with @tboerger that there is no technical issue there but perhaps from a user experience perspective it makes sense to use standard NPM variable names if possible.

**Comment by donny-dont** [comment]
Hi @jasonkarns the values can come from the yaml config or from Drone's secrets mechanism. That's why they don't match. In 0.5 the CLI is exclusively used to set all values and the npmrc is directly created.

I ran a bunch of things by the NPM guys during development and they didn't have any particular issues. If there's something specific that's a problem I'm fine with reopening.

**Comment by jasonkarns** [comment]
I'm just confused why the drone secrets mechanism doesn't use the same names as the standard npm env var names. It feels like needless misdirection that requires more documentation instead of using existing community knowledge that every node/npm dev would already have.

**Comment by tboerger** [comment]
> I'm just confused why the drone secrets mechanism doesn't use the same names as the standard npm env var names. It feels like needless misdirection that requires more documentation instead of using existing community knowledge that every node/npm dev would already have.

Because it's tied to the drone secret management, generic for all drone plugins and not tied to the specific npm naming convention.

**Comment by bradrydzewski** [comment]
> Because it's tied to the drone secret management, generic for all drone plugins and not tied to the specific npm naming convention.

This implies we _need_ the current secret names which is not necessarily true. Secret names are arbitrary and defined by the author and, in this case, could be changed.

> I'm just confused why the drone secrets mechanism doesn't use the same names as the standard npm env var names.

There is no reason to be confused. The author of the plugin chose the current variables names. Maybe the author has a reason for this. or maybe the author didn't know about the existing NPM environment variables. Does it really matter? If you feel strongly about it send a pull request.

**Comment by donny-dont** [comment]
@jasonkarns if its just some sort of confusion in terms of naming I'm not going to fix it. If I were to change it then its really ignoring multiple commands that are being set by the CLI. In which case if something were to change then someone would have to know the priority.
