### ISSUE TITLE
Build Issues with CGO / user.Current

### ISSUE THREAD

**Issue by steve-gray** [drone-plugins/drone-npm#17]
@tboerger / @donny-dont 

Was playing with the plugin and building locally since it's no published officially yet. In plugin.go @ 125 where reasoning about the user, the user.Current won't work - causing a panic - when CGO is disabled, as per:

  - https://github.com/golang/go/issues/6376

Manifests as:

    panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: runtime error: invalid memory address or nil pointer dereference
    main.writeNpmrc(0xc82007a690, 0xa, 0xc82007a6b0, 0xa, 0x0, 0x0, 0xc82008e560, 0x1d, 0xc82008e580, 0x1a, ...)
         /tmp/npm/drone-npm/plugin.go:125 +0x979

**Comment by donny-dont** [comment]
@bradrydzewski any thoughts on what we should do here to get things into alpine?

**Comment by bradrydzewski** [comment]
Change the image in the .drone.yml to the official Go Alpine image, and enable cgo

**Comment by bradrydzewski** [comment]
Or look at the git plugin. It doesn't have this issue and it writes a netrc
