### ISSUE TITLE
NPM root permission issue

### ISSUE THREAD

**Issue by guiguan** [drone-plugins/drone-npm#26]
When running under root, some script in `prepublish` might cause `cannot run in wd %s %s (wd=%s)` error.

Can you add `unsafe-perm = true` to the `.npmrc` to fix this issue?

**Comment by donny-dont** [comment]
Hi @guiguan. There are no guarantees that the `plugins/npm` image has everything needed to run any `publish` steps. See #5 .

**Comment by guiguan** [comment]
@donny-dont Maybe append to exist `.npmrc` instead of overwriting it?

**Comment by guiguan** [comment]
`unsafe-perm = true` is really handy for root docker environment :P
