### ISSUE TITLE
Update Request - Node 8.9.3 & NPM 5.5.1

### ISSUE THREAD

**Issue by metalix2** [drone-plugins/drone-npm#33]
Hi, 

I'm raising an issue to ask whether it would be possible to update the version of Node/NPM for the drone-npm plugin?

The current npm version `3.10.10` is almost a year behind and there are some new beneficial tasks that can be used in the newer version such as prepublishOnly to improve run and build times of deploying npm packages. In version `3.10.10` these tasks are run at `npm install` as well as `npm publish` see this [comment](https://github.com/npm/npm/issues/16685#issue-230521448) for a complete explanation.

In order to update to this you would need to upgrade your base image using `alpine 3.7` which contains these updated packages.

Let me know your thoughts of this update.

Kind regards,
Matt

**Comment by donny-dont** [comment]
Sure. Should we be pushing a different version number for this though?

**Comment by metalix2** [comment]
Yeah sure can? The only other thing I was unsure of, would have been whether the other plugins which use the drone-base would be effected or that they would all be updated if there was a newer version.

**Comment by tboerger** [comment]
> Yeah sure can? The only other thing I was unsure of, would have been whether the other plugins which use the drone-base would be effected or that they would all be updated if there was a newer version.

The other plugins are not automatically rebuilt, and so far it should be fine to update it.

**Comment by donny-dont** [comment]
After the change in drone-base lands I'll bump this to 1.1.0 just in case something horrible happens.

**Comment by tboerger** [comment]
@donny-dont sorry but I forgot to mention that you need to upgrade https://github.com/drone-plugins/drone-base/blob/amd64/Dockerfile#L1 instead of the master branch. The master branch doesn't provide the `plugins/base:amd64` image.

**Comment by metalix2** [comment]
Hey, just wanted to follow up on how this is going? I can see the base file has been updated to alpine3.7. Is all that is left is to rebuild this?

**Comment by tboerger** [comment]
Somebody still got to update https://github.com/drone-plugins/drone-base/blob/amd64/Dockerfile#L1 because this is the image used by this plugin.

**Comment by tboerger** [comment]
Just merged the pull request for the base image, we just need to trigger an update for this plugin, like merging the open pr from @donny-dont

**Comment by tboerger** [comment]
Can you confirm that your issue have been solved with latest image tag?

**Comment by metalix2** [comment]
Hi @tboerger, @donny-dont,

I'm happy to report that the latest image is now using node8 with npm version 5.5.1 👍 

Thanks again for your help!

Happy to close this Issue
