### ISSUE TITLE
npm whoami Timeout and build fails

### ISSUE THREAD

**Issue by segux** [drone-plugins/drone-npm#43]
When im trying to use drone-npm plugin for publish my package is failing when `npm whoami` is called.

This is the console error

npm whoami
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect
npm ERR! network connect ETIMEDOUT {IP}
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-09-26T11_39_29_239Z-debug.log
time="2018-09-26T11:39:29Z" level=fatal msg="Could not authenticate"

**Comment by tboerger** [comment]
That sounds like a simple network issue within your infrastructure.

**Comment by segux** [comment]
> That sounds like a simple network issue within your infrastructure.

Yes, sorry,  was a problem with docker
