### ISSUE TITLE
Multiple tag, from file

### ISSUE THREAD

**Issue by ADIX7** [drone-plugins/drone-npm#55]
In drone-docker there is option for multiple tags and also they can be in a file. I find it very usefull because a previous step can generate tags eg based on commit hash, branch name etc.

**Comment by tboerger** [comment]
@donny-dont what do you think about that? You are the NPM plugin master :)

**Comment by donny-dont** [comment]
I'm open to expanding capabilities but are multiple tags actually used in NPM? It isn't like docker in terms of tagging. NPM versions are semantic versioning and you can pass `--tag` to make the tag something other than `latest`. So for example you could have a `beta` track or `next` track. I don't think I've ever seen anyone want multiple dist tags on a single version though.
