### ISSUE TITLE
access setting is undocumented

### ISSUE THREAD

**Issue by nvdk** [drone-plugins/drone-npm#57]
This is more a feature request than a bug really (though I could make some arguments for it being a bug). 
I recently noticed that when trying to use this plugin for a new package that I run into the following error:

```
npm ERR! 402 Payment Required - PUT https://registry.npmjs.org/@lblod%2fember-rdfa-editor-roadsign-regulation-plugin - You must sign up for private packages
```

which makes sense since we don't have the option to pass the public flag. 

A possible solution would be to add a `public` parameter to the settings and default it to false for backwards compatibility

**Comment by nvdk** [comment]
Turns out there is an access setting! Could you please update the documentation to include the setting if it's supported?

https://github.com/drone-plugins/drone-npm/blob/827c3d9712732159196427bc703fb0b55dfbf5bd/cmd/drone-npm/config.go#L65

**Comment by tphoney** [comment]
https://github.com/drone/drone-plugin-index/pull/358 updates the docs for https://plugins.drone.io/plugins/npm

thanks @nvdk  !
