### ISSUE TITLE
Issue publishing scoped packages

### ISSUE THREAD

**Issue by leroyjware** [drone-plugins/drone-npm#7]
publish:
  npm:
    username: $NPM_USER
    password: $NPM_PASSWORD
    email: $NPM_EMAIL
    registry: XXX
    always_auth: true

We’re getting the following error:

npm info posttest XXXX
npm info ok 
[info] Pulling image plugins/drone-npm:latest
Drone NPM Plugin built from 9405d1a
Requesting XXXXXXX
Package already published
[info] Pulling image plugins/drone-cache:latest
Drone Cache Plugin built from 96d0472
Building cache node_modules

We’ve inspected your code and see that you’re not handling the error case. If publish returns true, you publish. Else, you simply print “Package already published”.

https://github.com/drone-plugins/drone-npm/blob/master/main.go#L141

Would it be possible for you to update your code so that you:
(1) URL encode before making the request to the NPM registry
(2) Handle the error returned by shouldPublishPackage more explicitly

We can submit a pull request if need be.

We’d love to use drone, but we’re blocked at the moment as all of our work depends on publishing scoped packages. We’d appreciate your help.

**Comment by tboerger** [comment]
I have not authored this plugin, but generally every contribution or improvement of the plugins is welcome. So if you can provide a pull request that would be awesome.

**Comment by donny-dont** [comment]
I'm the original author here. I can also do something about this. We currently run sinopia so I can test on that but we won't have an npm on-prem to test on yet.

**Comment by leroyjware** [comment]
@donny-dont We'd appreciate the help. I don't think we'll be able to submit a PR for it anytime soon.

**Comment by donny-dont** [comment]
@leroyjware I was not able to reproduce this with Sinopia. Are you using NPM on-prem? or something else?

**Comment by leroyjware** [comment]
@donny-dont We're using Artifactory.

**Comment by leroyjware** [comment]
@donny-dont We've been testing locally and we're able to publish to Sinopia from Drone. We're still getting "Package already published" everytime we attempt to publish to Artifactory. Since the publish to Sinopia is working, it appears that there's nothing wrong with the drone-npm plugin except the lack of error reporting. If/when you update the plugin with better error output, please let us know. Otherwise, we'll keep working on it here and update this thread when it's resolved. We appreciate the help.

**Comment by donny-dont** [comment]
@leroyjware I was updating my plugins for 0.5 would that be something you could try out with artifactory? If it works I can back port it for you.

**Comment by leroyjware** [comment]
That would be awesome. Can you provide us with a Docker image we can pull and test with?

**Comment by donny-dont** [comment]
I'm in the process of updating my slack-blame plugin. After that its npm and you should be able to run the images easily. I'll give instructions once I have it sorted out.

**Comment by leroyjware** [comment]
Will do.

**Comment by donny-dont** [comment]
@leroyjware can you check out the feature/0.5-update branch?

https://github.com/drone-plugins/drone-npm/blob/feature/0.5-update/README.md has instructions on how to run. Was working with scopes through sinopia for me in my tests.

**Comment by donny-dont** [comment]
Almost forgot. You can build the image if you do not have golang ready by doing

```
docker build --file=Dockerfile.alpine --rm=true -t plugins/npm .
```

**Comment by leroyjware** [comment]
@donny-dont We resolved this. It turned out to be a number of issues on our end. All is working fine now. We appreciate the help.

**Comment by donny-dont** [comment]
@leroyjware so I don't need to url encode the `@foo/bar` stuff? I made that change on the branch so just want to verify if its needed or not.

**Comment by leroyjware** [comment]
No, it's not. Everything works well with the existing plugin. It was an issue with publishing permissions, registry URL, and credentials. Once we got all of that set correctly, publishing works fine.

**Comment by donny-dont** [comment]
@leroyjware Thank you for the update I'll roll back that change. Glad you got it working!
